# Generated by Django 5.2.1 on 2025-05-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eigenfacesmodel',
            name='projected_faces',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eigenfacesmodel',
            name='training_labels',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
